using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;

namespace OneJS {
    /// <summary>
    /// Generates TypeScript definition files for pack objects.
    /// Enables intellisense for __pack('slug') access.
    /// </summary>
    public static class PackTypeGenerator {
        /// <summary>
        /// Header line prefix that records Pack.Version in the generated .d.ts.
        /// The .d.ts is rewritten on every extraction, so this line is how the editor
        /// tells whether extracted files match the current pack asset.
        /// </summary>
        public const string VersionLinePrefix = "// Version: ";

        // Common Unity type mappings
        static readonly Dictionary<Type, string> TypeMap = new Dictionary<Type, string> {
            // Primitives
            { typeof(int), "number" },
            { typeof(float), "number" },
            { typeof(double), "number" },
            { typeof(long), "number" },
            { typeof(short), "number" },
            { typeof(byte), "number" },
            { typeof(bool), "boolean" },
            { typeof(string), "string" },

            // Common Unity types: map to CS namespace
            { typeof(Texture2D), "CS.UnityEngine.Texture2D" },
            { typeof(Texture), "CS.UnityEngine.Texture" },
            { typeof(Sprite), "CS.UnityEngine.Sprite" },
            { typeof(Material), "CS.UnityEngine.Material" },
            { typeof(AudioClip), "CS.UnityEngine.AudioClip" },
            { typeof(GameObject), "CS.UnityEngine.GameObject" },
            { typeof(Transform), "CS.UnityEngine.Transform" },
            { typeof(Color), "CS.UnityEngine.Color" },
            { typeof(Color32), "CS.UnityEngine.Color32" },
            { typeof(Vector2), "CS.UnityEngine.Vector2" },
            { typeof(Vector3), "CS.UnityEngine.Vector3" },
            { typeof(Vector4), "CS.UnityEngine.Vector4" },
            { typeof(Quaternion), "CS.UnityEngine.Quaternion" },
            { typeof(Rect), "CS.UnityEngine.Rect" },
            { typeof(Bounds), "CS.UnityEngine.Bounds" },
            { typeof(AnimationCurve), "CS.UnityEngine.AnimationCurve" },
            { typeof(Gradient), "CS.UnityEngine.Gradient" },
            { typeof(ScriptableObject), "CS.UnityEngine.ScriptableObject" },
        };

        /// <summary>
        /// Generate TypeScript definitions for a pack's global objects.
        /// </summary>
        public static string Generate(Pack pack) {
            if (pack == null) return "// Error: null pack\nexport {};";

            var sb = new StringBuilder();

            sb.AppendLine($"// Auto-generated by OneJS Pack: {pack.Slug}");
            if (!string.IsNullOrEmpty(pack.Version)) {
                sb.AppendLine($"{VersionLinePrefix}{pack.Version}");
            }
            sb.AppendLine($"// {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            if (pack.Objects == null || pack.Objects.Count == 0) {
                sb.AppendLine("// No global objects defined in this pack");
                sb.AppendLine("export {};");
                return sb.ToString();
            }

            // Generate interface and __pack overload for this pack
            var path = pack.RelativePath;
            var interfaceName = ToPascalCase(pack.Slug) + "Pack";

            sb.AppendLine("declare global {");
            sb.AppendLine($"    interface {interfaceName} {{");

            foreach (var entry in pack.Objects) {
                if (string.IsNullOrEmpty(entry.key) || entry.value == null) continue;

                var tsType = GetTypeScriptType(entry.value.GetType());
                sb.AppendLine($"        {entry.key}: {tsType};");
            }

            sb.AppendLine("    }");
            sb.AppendLine($"    function __pack(path: '{path}'): {interfaceName};");
            // The names from before the rename, so code written against them still typechecks
            sb.AppendLine("    /** @deprecated Use __pack. */");
            sb.AppendLine($"    function __cart(path: '{path}'): {interfaceName};");
            sb.AppendLine($"    /** @deprecated Use {interfaceName}. */");
            sb.AppendLine($"    type {ToPascalCase(pack.Slug)}Cartridge = {interfaceName};");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("export {};");

            return sb.ToString();
        }

        /// <summary>
        /// Read the pack version recorded in a generated .d.ts, or null if absent.
        /// Only scans the leading comment header, so user edits below never match.
        /// </summary>
        public static string ParseVersion(string dtsText) {
            if (string.IsNullOrEmpty(dtsText)) return null;
            using var reader = new StringReader(dtsText);
            string line;
            while ((line = reader.ReadLine()) != null) {
                if (line.StartsWith(VersionLinePrefix, StringComparison.Ordinal)) {
                    return line.Substring(VersionLinePrefix.Length).Trim();
                }
                if (!line.StartsWith("//", StringComparison.Ordinal)) return null;
            }
            return null;
        }

        /// <summary>
        /// Map a C# type to its TypeScript equivalent.
        /// </summary>
        static string GetTypeScriptType(Type type) {
            if (type == null) return "any";

            // Check exact match first
            if (TypeMap.TryGetValue(type, out var mapped)) {
                return mapped;
            }

            // Check for ScriptableObject subclasses
            if (typeof(ScriptableObject).IsAssignableFrom(type)) {
                return GetFullTypeName(type);
            }

            // Check for Component subclasses
            if (typeof(Component).IsAssignableFrom(type)) {
                return GetFullTypeName(type);
            }

            // Check for UnityEngine.Object subclasses
            if (typeof(UnityEngine.Object).IsAssignableFrom(type)) {
                return GetFullTypeName(type);
            }

            // Fallback for unknown types
            return "any";
        }

        /// <summary>
        /// Get the full TypeScript type name with CS prefix.
        /// </summary>
        static string GetFullTypeName(Type type) {
            var fullName = type.FullName;
            if (string.IsNullOrEmpty(fullName)) return "any";

            // Handle nested types (replace + with .)
            fullName = fullName.Replace("+", ".");

            return $"CS.{fullName}";
        }

        /// <summary>
        /// Convert a kebab-case slug to PascalCase for interface names.
        /// </summary>
        static string ToPascalCase(string slug) {
            if (string.IsNullOrEmpty(slug)) return slug;

            var sb = new StringBuilder();
            var capitalizeNext = true;

            foreach (var c in slug) {
                if (c == '-' || c == '_') {
                    capitalizeNext = true;
                } else if (capitalizeNext) {
                    sb.Append(char.ToUpperInvariant(c));
                    capitalizeNext = false;
                } else {
                    sb.Append(c);
                }
            }

            return sb.ToString();
        }
    }
}
