using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEngine;

namespace OneJS.Editor.TypeGenerator {
    /// <summary>
    /// Declares each object in a JSRunner's Globals list for TypeScript, in
    /// types/jsrunner.d.ts beside types/csharp.d.ts, so an app never hand-writes
    /// `declare const ghostPrefab: CS.UnityEngine.GameObject`.
    ///
    /// Each entry is declared as its object's C# type when the app's typings
    /// declare that type, and otherwise as the nearest base type they do, ending
    /// at CS.UnityEngine.Object. "The app's typings" means what its TypeScript
    /// actually compiles against: unity-types in node_modules and the runner's
    /// generated csharp.d.ts, read rather than assumed, so a type is never named
    /// that tsc cannot find.
    /// </summary>
    public static class GlobalsTypings {
        /// <summary>
        /// Named for where the declarations come from, as csharp.d.ts is, and far
        /// enough from the app's own global.d.ts that neither is mistaken for the other.
        /// </summary>
        public const string FileName = "jsrunner.d.ts";

        /// <summary>Every chain ends here: every Globals value is a UnityEngine.Object.</summary>
        public const string RootType = "CS.UnityEngine.Object";

        const string Header =
            "// Generated by OneJS from this JSRunner's Globals list, whenever it changes.\n" +
            "// Do not edit: add, rename or remove a global in the inspector instead.\n";

        static readonly Regex Identifier = new Regex(@"^[A-Za-z_$][A-Za-z0-9_$]*$");

        static readonly HashSet<string> Reserved = new HashSet<string> {
            "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do",
            "else", "enum", "export", "extends", "false", "finally", "for", "function", "if", "import", "in",
            "instanceof", "new", "null", "return", "super", "switch", "this", "throw", "true", "try", "typeof",
            "var", "void", "while", "with", "let", "static", "yield", "await", "implements", "interface",
            "package", "private", "protected", "public", "arguments", "eval", "undefined",
        };

        /// <summary>
        /// The file's text for these entries, or null when there is nothing to declare. `declared` holds the C# full names
        /// (nested types joined with '.') that the app's typings declare under CS.
        /// Entries run in order and a later one with the same key wins, as at runtime;
        /// an entry with no key or no object is skipped, as at runtime.
        /// </summary>
        public static string Generate(IEnumerable<GlobalEntry> entries, ISet<string> declared) {
            var byKey = new Dictionary<string, UnityEngine.Object>();
            var order = new List<string>();
            foreach (var entry in entries ?? Enumerable.Empty<GlobalEntry>()) {
                if (entry == null || string.IsNullOrEmpty(entry.key) || entry.value == null) continue;
                if (!byKey.ContainsKey(entry.key)) order.Add(entry.key);
                byKey[entry.key] = entry.value;
            }

            if (order.Count == 0) return null;
            var sb = new StringBuilder(Header).Append('\n');
            foreach (var key in order) {
                var type = byKey[key].GetType();
                if (!Identifier.IsMatch(key) || Reserved.Contains(key)) {
                    sb.Append($"// \"{key}\" is not a name a declaration can have, so read it as globalThis[\"{key}\"].\n");
                    continue;
                }
                var tsType = TsTypeOf(type, declared);
                var line = $"declare const {key}: {tsType}";
                if (tsType != TsName(type)) {
                    line += $" // a {CsName(type)}: add its assembly to Typing Assemblies to type it exactly";
                }
                sb.Append(line).Append('\n');
            }
            return sb.ToString();
        }

        /// <summary>The type's own TS name if the typings declare it, else its nearest declared base, else CS.UnityEngine.Object.</summary>
        public static string TsTypeOf(Type type, ISet<string> declared) {
            for (var t = type; t != null && t != typeof(UnityEngine.Object); t = t.BaseType) {
                if (t.IsGenericType) continue;
                if (declared != null && declared.Contains(CsName(t))) return TsName(t);
            }
            return RootType;
        }

        static string CsName(Type type) => type.FullName?.Replace('+', '.');
        static string TsName(Type type) => "CS." + CsName(type);

        /// <summary>
        /// Writes `content` to `path` unless the file already holds exactly that, and
        /// for null content removes a file this class wrote, leaving anyone else's.
        /// Returns whether the file changed.
        /// </summary>
        public static bool WriteIfChanged(string path, string content) {
            if (content == null) {
                if (!File.Exists(path) || !File.ReadAllText(path).StartsWith(Header, StringComparison.Ordinal)) return false;
                File.Delete(path);
                return true;
            }
            if (File.Exists(path) && File.ReadAllText(path) == content) return false;
            var dir = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
            File.WriteAllText(path, content);
            return true;
        }

        /// <summary>
        /// Writes the runner's jsrunner.d.ts beside its csharp.d.ts, or removes it once
        /// the Globals list is empty, so an app with no globals has no such file.
        /// Returns whether the file changed; false also when the runner has no working directory yet.
        /// </summary>
        public static bool WriteFor(JSRunner runner) {
            var typings = runner != null ? runner.TypingsFullPath : null;
            if (typings == null || runner.WorkingDirFullPath == null || !Directory.Exists(runner.WorkingDirFullPath)) return false;
            var path = Path.Combine(Path.GetDirectoryName(typings) ?? runner.WorkingDirFullPath, FileName);
            return WriteIfChanged(path, Generate(runner.Globals, DeclaredTypes(runner)));
        }

        /// <summary>The C# types the runner's app can name under CS: unity-types' and its own csharp.d.ts.</summary>
        public static HashSet<string> DeclaredTypes(JSRunner runner) {
            var declared = new HashSet<string>();
            var unityTypes = Path.Combine(runner.WorkingDirFullPath, "node_modules", "unity-types");
            if (Directory.Exists(unityTypes)) {
                foreach (var file in Directory.GetFiles(unityTypes, "*.d.ts")) ReadDeclared(File.ReadAllText(file), declared);
            }
            var own = runner.TypingsFullPath;
            if (own != null && File.Exists(own)) ReadDeclared(File.ReadAllText(own), declared);
            return declared;
        }

        static readonly Regex NamespaceLine = new Regex(@"^(?:export\s+)?(?:declare\s+)?namespace\s+([\w.]+)\s*\{");
        static readonly Regex TypeLine = new Regex(@"^(?:export\s+)?(?:declare\s+)?(?:abstract\s+)?(?:class|interface|enum)\s+([A-Za-z_$][\w$]*)");

        /// <summary>
        /// Adds the full names of the classes, interfaces and enums declared under
        /// `namespace CS` in OneJS's generated .d.ts text, without the CS prefix.
        /// The emitter writes one declaration per line with balanced braces, so
        /// tracking namespace blocks by brace depth is exact for its output.
        /// </summary>
        public static void ReadDeclared(string dts, ISet<string> into) {
            var stack = new List<(string name, int depth)>();
            var depth = 0;
            using var reader = new StringReader(dts);
            string raw;
            while ((raw = reader.ReadLine()) != null) {
                var line = raw.Trim();
                var ns = NamespaceLine.Match(line);
                // Directly inside the innermost namespace, or at the top level: not inside a type's body.
                var direct = depth == (stack.Count == 0 ? 0 : stack[stack.Count - 1].depth + 1);
                if (ns.Success && direct) {
                    stack.Add((ns.Groups[1].Value, depth));
                } else if (direct) {
                    var type = TypeLine.Match(line);
                    if (type.Success && stack.Count > 0 && stack[0].name.Split('.')[0] == "CS") {
                        var path = string.Join(".", stack.Select(s => s.name)) + "." + type.Groups[1].Value;
                        into.Add(path.Substring(3));
                    }
                }
                foreach (var c in line) {
                    if (c == '{') depth++;
                    else if (c == '}') {
                        depth--;
                        while (stack.Count > 0 && stack[stack.Count - 1].depth >= depth) stack.RemoveAt(stack.Count - 1);
                    }
                }
            }
        }
    }
}
